### ISSUE TITLE
Opening vim plugins fails in neovim

### ISSUE THREAD

**Issue by flipsi** [stsewd/gx-extended.vim#10]
I had a custom vim function to open Github URLs for vim plugins from within my vimrc - then I found this plugin and thought "Great - let's use this instead!"

However it does not work as expected. If I hit `gx` on a vim-plug style line like
```
Plug 'tpope/vim-obsession'
```
I will get an error like:
```
vim.ui.open: command failed (2): { "xdg-open", "tpope/vim-obsession" }
```

Is this a bug or am I missing something?

I'm on the latest Neovim:
```
> nvim --version
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1720049189
Run "nvim -V1 -v" for more info
```

Thanks in advance!

**Comment by stsewd** [comment]
Hi, doesn't look like you are using this plugin at all. Neovim now defaults to map `gx` to vim.ui.open, this plugin doesn't create mappings by default if they are already defined

https://github.com/stsewd/gx-extended.vim/blob/6a338c93449ad972d0148396cefbc95ccbe6c653/doc/gx-extended.txt#L110

You need to explicitly create the mappings for gx to use this plugin.

**Comment by flipsi** [comment]
I feel stupid now. :laughing: 

I explicitly added a mapping and it works smoothly.

Thank you for taking the time to respond in such a kind way :pray:
