### ISSUE TITLE
"normal" gx behaviour not working

### ISSUE THREAD

**Issue by bergtholdt** [stsewd/gx-extended.vim#3]
In my markdown document I have included some images like

```markdown
  ![abdomen](media/abdomen.png)
```

using gx on the image filename does nothing. I expected it to open the file in the default viewer.

In gx-extended.vim/autoload/gxext/global/gx.vim I find

```vim
  if !g:gxext#dryrun
    return 1
  endif
```

I.e. when dryrun is not set it will immediately return. If I negate the condition

```vim
  if g:gxext#dryrun
    return 1
  endif
```

My image get's opened in the default viewer. Is this meant to **not** activate netrw@BroseX when dryrun == 0?

**Comment by stsewd** [comment]
That was definitely not indented! Thanks for spotting that bug!
